## assumes virtualenv is already installed
#- name: install python-virtualenv
#  command: pip install virtualenv

- name: checkout virtualbmc (vbox patched version)
  shell: |
    git clone https://github.com/kskmori/virtualbmc-vbox
    cd virtualbmc-vbox
    git checkout {{ VBMC_VERSION }}
  become: false

- name: create virtual env
  shell: |
    virtualenv {{ VBMC_VENV_DIR }}
    . {{ VBMC_VENV_DIR }}/bin/activate
    pip install --upgrade pip
    pip install -e ./virtualbmc-vbox/
    deactivate
  become: false

