- hosts: 127.0.0.1
  connection: local
  become: true
  max_fail_percentage: 0

  roles:
    - role: wsl2-subnet-setup
      when: ansible_os_family == 'Debian' and 'microsoft-standard' in ansible_kernel
      tags: wsl2

    - role: vbmcd-start
      tags: always

    - role: vbmc-add
      tags: always
