- hosts: 127.0.0.1
  connection: local
  become: true
  max_fail_percentage: 0

  tasks:
  - name: stop and delete for each hacluster nodes
    include_role:
      name: vbmc-delete
    with_items: "{{ groups['hacluster_vbmc'] }}"
    loop_control:
      loop_var: nodename
    # always tag is to enable tags inside include_role
    #  https://github.com/ansible/ansible/issues/34196#issuecomment-371863179
    tags: always

  - name: stop vbmcd daemon
    include_role:
      name: vbmcd-stop
    tags: always
